### ISSUE TITLE
PRs and NuGet

### ISSUE THREAD

**Issue by lethek** [mikkoha/task-cache#1]
Hi Mikko,

I forked this project and made some updates for use in a project a couple of years ago. At the time I published it as a NuGet package in a private feed.

However, I've got a need for this kind of functionality in a couple of other projects recently and have dug the code back up again.

Would you be open to taking pull-requests and publishing a NuGet package to nuget.org to make it more readily accessible? If you don't have the time or inclination for that, I'm happy to help out in any way you like.

**Comment by mikkoha** [comment]
Hi Michael, although it would be interesting, I don't have time to learn how to publish a NuGet package right now. If you're willing to do the work, can I make you a maintainer of this repo? Or what would you suggest?

**Comment by lethek** [comment]
Thanks Mikko, I'm happy to do everything myself as either a maintainer of your repo or my own repo if you prefer to keep yours as-is.

If the original code were mine I would do it anyway, but because the code I'm using is based on yours and it's still substantially yours, I don't want to publish anything on publicly available channels without your permission.

**Comment by mikkoha** [comment]
I appreciate your consideration of the fact that I created the original code. I've sent you an invite to be a collaborator in this repo. I guess I have to wait for you to accept before I can fine-tune your role to be a maintainer (I didn't see an option for that now). Let me know if you need anything else to continue the work on this repo.

**Comment by lethek** [comment]
Thanks! I've just accepted the invitation. Github says "You now have push access to the mikkoha/task-cache repository". I'll let you know if I need anything else.

I'm on my mobile phone right now, but will take a look tomorrow from my pc.

**Comment by mikkoha** [comment]
Great! Feel free to make the changes you need.

**Comment by lethek** [comment]
One important question I should have asked earlier: is there any particular license you want to give it?

**Comment by mikkoha** [comment]
I'd say MIT if one needs to be picked.

**Comment by lethek** [comment]
Great- I'll put an MIT license on it.

That's the one I usually pick too when I have a choice for an open source project.

**Comment by lethek** [comment]
It's done now. There are two packages you can find if you search for **TaskCaching**:
* **TaskCaching**: has ITaskCache and TaskCache class, but depends on the other package to do the work.
* **TaskCaching.Microsoft.Extensions.Caching.Memory**: simply adds GetOrCreateTask extension method to the MemoryCache class (the Microsoft.Extensions.Caching.Memory one rather than the old System.Runtime.Caching one).

If you have a nuget.org account, let me know your username and I'll add you as a package owner.
